### PR TITLE
Added new option to skip non classes[0-9]*.dex files

### PR DESCRIPTION
**Pull request by danielmalmq**

### CODE REVIEW

**Comment by iBotPeaches** [comment]
How often do you run into applications where you want the `classes[0-9]*.dex` files but don't want other named ones?

**Comment by iBotPeaches** [comment]
Sorry for the delay on this. Real curious on the usecase here. I'd rather not pollute the configuration namespace as that is already messy. I don't see why would you ever want the dex0-9 files, but not any others

**Comment by danielmalmq** [comment]
Hey, so the reason behind this PR is that I had to modify the smali code of a given app. The app in question had a bunch of extra dex files in /assets. Some of which duplicated code which causes ApkTool to not be able to recompile it. And as I was only interested in recompiling the main dex files I created this PR.

Have a look at the test apk I created and added as part of the PR which reproduced this issue if you are unsure of what is happening.

**Comment by iBotPeaches** [comment]
Okay, I'm going to sit on this. I'm real fearful of bloating root configuration namespace and not sure this feature warrants a feature flag. I might break it down to a sub configuration like "--only-main-classes"

**Comment by iBotPeaches** [comment]
Closing this one for superseded - https://github.com/iBotPeaches/Apktool/pull/2132. Thank you for the initial contribution!

**Pull request closed without merging**
