### PR TITLE
feat: introduce SDK_S_V2

### PR DESCRIPTION
**Pull request by iBotPeaches**
fixes: #2776

### CODE REVIEW

**Review by Doni108 — COMMENTED** [review]
Ok

**Review by Doni108 — COMMENTED** [review]
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java

**Review by Doni108 — COMMENTED** [review]
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java

**Comment by Doni108** [comment]
brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java

**Comment by iBotPeaches** [comment]
@Doni108 - What are you doing? I woke up to nearly 20 emails from you just leaving "Ok" and random filenames on PRs.

**Pull request merged**
