### PR TITLE
new: featureFlags support for SDK 35 apps

### PR DESCRIPTION
**Pull request by IgorEisberg**
This records all featureFlag attrs that were enabled when the APK was originally built. This is now required by AAPT2 to pass these flags and their enabled/disabled state if they are used in AndroidManifest.xml.
The flags are recorded to apktool.yml and can be configured, if so desired. In normal usage, all flags should remain set to true (i.e. enabled). Sample APK sourced from AOSP Android 15.

[https://drive.google.com/file/d/1av7Ih7-YUXi73Hf0E3xlPv-V-nE_sXdt/view](https://drive.google.com/file/d/1av7Ih7-YUXi73Hf0E3xlPv-V-nE_sXdt/view)

### CODE REVIEW

**Review by iBotPeaches — COMMENTED** [review]
I believe we'll need to add a sample test for this to ensure we can decode/build it. So we can adapt the testapp or a new apk sample.

**Review by iBotPeaches — APPROVED** [review]

**Comment by iBotPeaches** [comment]
thanks!

**Comment by Jon8RFC** [comment]
If it's helpful, the NFC apk from Android 15 on a Pixel 9 Pro XL fails to build with the current apktool snapshot:
```
I: Using Apktool v2.10.0-25-f8092846-SNAPSHOT on NfcNciApexGoogle_mod.apk with 8 threads
I: Smaling smali folder into classes.dex...
I: Building resources with aapt2...
W: error: attribute 'android:featureFlag' has flag 'com.android.nfc.flags.enable_direct_boot_aware' not found in flags from --feature_flags parameter.
```
⠀
⠀
If I remove both of these from the manifest entirely, then it builds without error:
```
android:featureFlag="com.android.nfc.flags.enable_direct_boot_aware"
android:featureFlag="!com.android.nfc.flags.enable_direct_boot_aware"
```
⠀
⠀
Attached is the apk in question, located here:
```
/apex/com.android.nfcservices/priv-app/NfcNciApexGoogle@AP4A.241205.013/NfcNciApexGoogle.apk
/apex/com.android.nfcservices@352090000/priv-app/NfcNciApexGoogle@AP4A.241205.013/NfcNciApexGoogle.apk
```
[NfcNciApexGoogle.zip](https://github.com/user-attachments/files/18402006/NfcNciApexGoogle.zip)

**Comment by iBotPeaches** [comment]
I turned this discussion into a new bug since we are just commenting on a merged PR and it got lost.

**Comment by Tulsadiver** [comment]
Thank you, sir!

I was also wondering what happened to the missing attributes problem.  Even after fixing the feature flag errors, the dozens of attribute problems show up....

Compiling first pass...
I: Using Apktool v2.11.0-3-4b2c9abe-SNAPSHOT on SystemUIGoogle.apk with 4 threads
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Building resources with aapt2...
W: E:\3Custom14Pixelscript\SystemUIGoogle\res\animator\design_appbar_state_list_animator.xml:4: error: attribute state_liftable (aka com.android.systemui:state_liftable) not found.
W: E:\3Custom14Pixelscript\SystemUIGoogle\res\animator\design_appbar_state_list_animator.xml:4: error: attribute state_lifted (aka com.android.systemui:state_lifted) not found.
W: E:\3Custom14Pixelscript\SystemUIGoogle\res\animator\m3_appbar_state_list_animator.xml:4: error: attribute state_liftable (aka com.android.systemui:state_liftable) not found.
W: E:\3Custom14Pixelscript\SystemUIGoogle\res\animator\m3_appbar_state_list_animator.xml:4: error: attribute state_lifted (aka com.android.systemui:state_lifted) not found.
W: E:\3Custom14Pixelscript\SystemUIGoogle\res\animator\m3_card_elevated_state_list_anim.xml:7: error: attribute state_dragged (aka com.android.systemui:state_dragged) not found.
W: E:\3Custom14Pixelscript\SystemUIGoogle\res\animator\m3_card_state_list_anim.xml:7: error: attribute state_dragged (aka com.android.systemui:state_dragged) not found.
W: E:\3Custom14Pixelscript\SystemUIGoogle\res\animator\mtrl_card_state_list_anim.xml:4: error: attribute state_dragged (aka com.android.systemui:state_dragged) not found.
W: E:\3Custom14Pixelscript\SystemUIGoogle\res\color\m3_card_foreground_color.xml:5: error: attribute state_dragged (aka com.android.systemui:state_dragged) not found.
W: E:\3Custom14Pixelscript\SystemUIGoogle\res\color\m3_card_stroke_color.xml:9: error: attribute state_dragged (aka com.android.systemui:state_dragged) not found.
W: E:\3Custom14Pixelscript\SystemUIGoogle\res\color\mtrl_card_view_foreground.xml:5: error: attribute state_dragged (aka com.android.systemui:state_dragged) not found.
W: E:\3Custom14Pixelscript\SystemUIGoogle\res\color\mtrl_card_view_foreground.xml:6: error: attribute state_dragged (aka com.android.systemui:state_dragged) not found.
W: E:\3Custom14Pixelscript\SystemUIGoogle\res\color\mtrl_card_view_ripple.xml:5: error: attribute state_dragged (aka com.android.systemui:state_dragged) not found.
W: E:\3Custom14Pixelscript\SystemUIGoogle\res\layout\status_bar_expanded.xml:10: error: attribute viewType (aka com.android.systemui:viewType) not found.
W: error: failed linking file resources.

**Pull request merged**
