### PR TITLE
Fix null pointer

### PR DESCRIPTION
**Pull request by a-bahmani**
When I am decompiling an apk, I got this exception:
Exception in thread "main" java.lang.NullPointerException
        at brut.androlib.res.data.ResResSpec.<init>(ResResSpec.java:42)

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Hi,

Do you have an application or associated bug report for this? Sometimes NPE are indications of larger issues at play and patching them at the NPE source might not always be the best method.

I'd prefer to dig into the error and path that led to this error then to patch out the NPE.

Thanks for the PR!

**Comment by a-bahmani** [comment]
Hi, 
I tried to decompile "Linkedin" apk from this [source](https://play.google.com/store/apps/details?id=com.linkedin.android&hl=en_US).
I used latest version of Apktool with this command:
`java -Xmx2048m -jar apktool.jar -f d C:/linkedin.apk -o C:/linkedin_mod
`
And I got this error:
```
I: Using Apktool 2.3.4 on linkedin.apk
I: Loading resource table...
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.ResResSpec.<init>(ResResSpec.java:42)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:308)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:260)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:175)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:131)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:741)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:228)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:164)
	at brut.apktool.Main.main(Main.java:73)
```

My best guess is the "name" variable at line 42 should be null and `name.isEmpty()` is not right here. It must be `name == null || name.isEmpty() `to check empty of the variable.

**Comment by iBotPeaches** [comment]
Thanks for the additional information. I will take a look over this holiday break.

**Comment by iBotPeaches** [comment]
Sorry for the delay. Had some time this morning and took a look and can't seem to replicate this crash.

```
➜  1959 apktool d com.linkedin.android_96913_apps.evozi.com.apk 
I: Using Apktool 2.4.0-0efccc-SNAPSHOT on com.linkedin.android_96913_apps.evozi.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  1959 apktool b com.linkedin.android_96913_apps.evozi.com
I: Using Apktool 2.4.0-0efccc-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  1959 
```

**Pull request merged**
