### PR TITLE
checking for null references in ResStyleValue

### PR DESCRIPTION
**Pull request by peter23**

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Is there a bug you are referencing or trying to fix? I ask just so I can examine the application myself. I recently (in 2.2.0) patched a null parent reference problem with `styles.xml`, so I understand how these issues come into play.

Thanks for the PR, I see where you were going but I think I'll hold off until I can cross check with an apk and research.

**Comment by peter23** [comment]
Basically it is not a fix, but just more informative message for some broken apk.
I had the same error as in https://github.com/iBotPeaches/Apktool/issues/1178 and https://github.com/iBotPeaches/Apktool/issues/1260.
I researched it and found that there are broken references in resources.arsc (I'll write more details in those issues).
After this commit https://github.com/iBotPeaches/Apktool/commit/00abedfa063db4644c87fe2d0feb2243220e0719 apktool does not show UndefinedResObject exception anymore, but just NullPointerException on this line [ResStyleValue.java#L58](https://github.com/iBotPeaches/Apktool/blob/master/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResStyleValue.java#L58). It is because `spec` is null.
So I made this fix to show more informative message.

**Comment by iBotPeaches** [comment]
Thanks for research. I took that route, because I want apktool to decode as much as possible. An UndefinedResource could be an intentional effort by application makers to thwart apktool, as Android once compiled, an unused resource, won't cause any problems.

While you have a more descriptive output, I'll probably take the route of trying to catch it and replacing it with a proper replacement. (`@null`, etc)

**Comment by iBotPeaches** [comment]
Superseded by this - https://github.com/iBotPeaches/Apktool/commit/c1cb9425d5f217beb273dee5a7cea7b0c9aa9b28

Thanks for the PR.

**Comment by peter23** [comment]
Could you please show log message for such references (now they are silently ignored)? I think it is useful to know about them. Like this: http://pastebin.com/cAFZXrnP (or I can make pull request if you prefer)

**Comment by iBotPeaches** [comment]
@peter23 Sure, open a pull request and we can get it merged. Since INFO only fires in verbose mode that seems fine to me.

**Pull request closed without merging**
