### PR TITLE
Correct regressions towards apktool.yml generation

### PR DESCRIPTION
**Pull request by iBotPeaches**
fixes: #3169 

* [x]  `mApkFileName` should return to `apkFileName`
* [x]  `mSdkInfo` should return to `sdkInfo`
* [ ]  ~~`resourcesAreCompressed` was what `compressionType`, fall back for the old~~
* [x]  `sdkInfo.*` missing is because `minSdkVersion` will overwrite all

### CODE REVIEW

**Comment by iBotPeaches** [comment]
`compressionType` is just hard-coded to false. It appears that broke between 2.0.0 and 2.1.0 when we removed the Zip64 stuff, which meant we no longer parsed the `resources.arsc` to check for stored/deflate.

So not sure if I should bring that back or just keep status quo for keep it as false.

**Comment by sv99** [comment]
> `compressionType` is just hard-coded to false. It appears that broke between 2.0.0 and 2.1.0 when we removed the Zip64 stuff, which meant we no longer parsed the `resources.arsc` to check for stored/deflate.
> 
> So not sure if I should bring that back or just keep status quo for keep it as false.
> 
> Regression occurred back here for compressionType: [v2.0.1...v2.0.2](https://github.com/iBotPeaches/Apktool/compare/v2.0.1...v2.0.2)

In the master branch decode - build worked without exception.
 
I have not found an opportunity to make a synonym for the field in the snakeyaml.
I think we may make custom serializer to yaml without using any library - structure very simple.

**Comment by iBotPeaches** [comment]
> In the master branch decode - build for this apk worked without exception.

Yeah its tough to notice since a newly decoded application would generate a `apktool.yml` that the build understood. Probably more noticable for these various tools that swap versions or rebuild versions from previously decoded files. I don't think there is a bug with build - just a regression of the property names.

> I have not found an opportunity to make a synonym for the field in the snakeyaml. I think we may make custom serializer to yaml without using any library - structure very simple.

Not sure I follow - I was going to try and prefer `resourcesAreCompressed` if its set and fall back to `compressionType` if its not found. However, the typing of the properties probably makes that difficult since neither would be nullable.

**Comment by iBotPeaches** [comment]
Not going to make any changes at the moment for the compression ones. They've been broken for years, but I'll add it back even though its false 100% of the time.

**Pull request merged**
