### PR TITLE
fix the bug, the code want to get NO_COMPRESS files, but added COMPRE…

### LINKED ISSUE #1577: NO_COMPRESS_PATTERN has bug
there is a bug in Androlib.java
in the line of 169
`if (isAPKFileNames(file) && !NO_COMPRESS_PATTERN.matcher(file).find())`
the logic want to get the list of NO_COMPRESS files, but in fact, it gets the list of COMPRESS files!

### PR DESCRIPTION
**Pull request by realityJie**
fixes #1577

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Thanks for the PR.

Do you have an application that experienced this bug? Or was this an audit of the code in which you found a problem? This in my knowledge (while the code looks confusing) is working as intended.

**Comment by realityJie** [comment]
show the problem for you

**Comment by realityJie** [comment]
I show the problem for you
07292de5-cf15-409f-a7c3-164ce0984159

**Comment by iBotPeaches** [comment]
Thanks for the details. I will need to make an example in order to add a unit-test to prevent regression.

**Comment by iBotPeaches** [comment]
I added two files (json/png) at maximum compression into the application and made these unit tests - https://github.com/iBotPeaches/Apktool/commit/a1cb15d721f2a03a1ad03a5c5f0a46b1384dd031

Passes on current master. If your JSON files in original application were STORED. They will be STORED in the final apk. I don't think this needs to be changed unless you have a failing unit test to accompany it.

**Comment by realityJie** [comment]
I show you my application, which is a GAME APP:
[http://res.youyunad.com/cloud_pack/outputs/qlyyx/qlyyx_agent_102483_yyb_ysdk_dalan_177_1.0_20170728_12108.apk](url)
In this application, these are some resources like json，lua, and these resources should be compressed, but in fact it was't!
So after decompile the APK, the size of APK increase 50M! 
My environment:
APKTool version:2.2.4
OS: ubuntu14.04.LTS
JDK: openJDK  "1.8.0_141"

**Comment by iBotPeaches** [comment]
Some of these files are stored, some are deflated.

```
   13094  Stored    13094   0% 01-01-1980 08:00 1a42a0b9  assets/src/app/protocol/networld.lua
    6170  Defl:N     1974  68% 01-01-1980 08:00 85f3191c  assets/src/app/resetgame.lua
```

Or JSON
```
   29811  Defl:N     2677  91% 01-01-1980 08:00 5e9fb8c3  assets/res/ui/world_minimap.json
  109368  Defl:N     5948  95% 01-01-1980 08:00 ea3bc578  assets/res/ui/worldview.json
       0  Stored        0   0% 01-01-1980 08:00 00000000  assets/statistics/Junhai.json
       8  Stored        8   0% 01-01-1980 08:00 953f2ada  assets/statistics/statistics.json
```

You just switched the boolean around, this is not the correct fix. As detailed by my unit-test, things are working correctly.

You have hit #1272, I am going to close this. Thanks for attempting a fix though! The problem is much larger than this.

**Pull request closed without merging**
