### PR TITLE
Added some resources that I have found useful

### PR DESCRIPTION
**Pull request by vicdeaj**
I don't know if I shouldn't have checked in the gemfile.lock. Anyways, I have added to the documentation some links which I have found useful while researching android apks. Maybe they are a bit old, but I think that they are still applicable today

### CODE REVIEW

**Review by iBotPeaches — COMMENTED** [review]
Just leaving a generic comment that I read this. It appears this PR is doing many things
 * updating dependencies
 * changing build command (type or upgrade?)
 * adding a new category about AXML
 * adding links to framework files
 
 
 A few of these points I want to think about it and others I have to research.

**Comment by iBotPeaches** [comment]
Not sure right now if I want to take this all at once. I'm not feeling a whole new page for AXML and instead rather just adding it to the intro section.

I'm also a bit fearful with so many new links - they always decay over time and then I have to remember what they served and how they are purposed.

**Comment by vicdeaj** [comment]
Definitely link decaying is an issue, Maybe adding a section at the end with useful links and a short description would be the right call?

About AXML, maybe adding it to the introduction for now is the right call

About changing the build command, I just though that serve was a typo but it seems like it wasn't so I will fix it

**Comment by iBotPeaches** [comment]
Okay, lets do this. Any official link (Github, AOSP, etc) - keep, but lets try and make it part of the intro or the decode/build section as to not introduce a different page.

Additionally, if you want to split the dependency updates into its own PR - I can just instant merge that one.

**Review by iBotPeaches — CHANGES_REQUESTED** [review]
Just conflicts to resolve now after merging the last one.

**Comment by iBotPeaches** [comment]
Closing - I did get the dependency update, but the other changes here sub the dep update I don't think we need.

**Pull request closed without merging**
