### PR TITLE
Expose the aapt --no-crunch option

### PR DESCRIPTION
**Pull request by Novex**
Adds a --no-crunch/-nc flag to apktool which gets passed through to aapt. This allows apktool to make a byte-for-byte copy of resource files which lowers the amount of changes when generating patches.

Happy to add tests if you can point me in the right direction - I'm not super familiar with the java ecosystem and I couldn't find any existing ones that included `aaptPackage`.

Also there was a feature request for this in #1232, which is already closed anyway.

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Thanks for the pull-request. I'm not sure of a way to test this efficiently. I might run a little test locally with an image to detect modifications, otherwise I'll get this merged.

**Comment by iBotPeaches** [comment]
Going to need to dig into this more. `no-crunch` is destroying 9patch images.

Original
```
testapp-orig/res/drawable-xxhdpi/ic_notification_overlay.9.png
```

Rebuilt w/ `--no-crunch`

```
testapp-new/res/drawable-xxhdpi/ic_notification_overlay.png
```

It wiped the `.9.` portion of URL, thus tests failed.

**Comment by Novex** [comment]
I've only tested with one apk, but my 9patch images seem to be rebuilt ok. I think it's not using aapt2 if that helps narrow it down.

**Comment by lexmann** [comment]
What's going ring her

**Comment by iBotPeaches** [comment]
This has been merged in.

**Pull request closed without merging**
