### PR TITLE
Prevents double escaping of special chars in plurals items

### PR DESCRIPTION
**Pull request by PiR43**
Sme problem than https://github.com/iBotPeaches/Apktool/commit/f93a3123080ef9bacdb1e56bc1fa0a6169b4285d but for plurals items)

### CODE REVIEW

**Comment by PiR43** [comment]
I have tested it with an apk who has the folowing resource:
    <plurals name="content">
        <item quantity="other">Vous disposez de &lt;font color=#8c593c>%1$d contenus&lt;/font> sur &lt;font color=#8c593c>%2$d disponibles&lt;/font></item>
        <item quantity="one">Vous disposez de &lt;font color=#8c593c>%1$d contenu&lt;/font> sur &lt;font color=#8c593c>%2$d disponibles&lt;/font></item>
    </plurals>

Without this patch the "&lt;" are replaced by "&amp;lt;"

**Comment by ingbrzy** [comment]
Can be used same also for strings.xml to keep "<" ">" in html tags ?

https://github.com/iBotPeaches/Apktool/blob/64644a1242d47d8f69fb358f590b4312eeab5a12/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResStringValue.java#L51

**Comment by PiR43** [comment]
@ingbrzy encodeAsResXmlNonEscapedItemValue was created for item (according to its name). I don't know if using it for string could be dangerous or not. I let someone who know well this project answer.

**Comment by iBotPeaches** [comment]
Sorry about the delay. I took a few weeks off apktool for sanity. I'll get on this soon and the tracker here.

**Comment by iBotPeaches** [comment]
Sorry for mega delay. Gave this a shot and maybe I don't understand it. I added this test suite - https://github.com/iBotPeaches/Apktool/commit/5e94801de11aea5b351422db8dfb1332746ff291

and its passing on current master. Did I interpret that wrong?

**Comment by iBotPeaches** [comment]
Closing this, could not replicate with my test suite - https://github.com/iBotPeaches/Apktool/commit/5e94801de11aea5b351422db8dfb1332746ff291

If I was wrong, feel free to respond and I can take another look.

**Comment by PiR43** [comment]
Yes I confirm that on 2.2.3 this problem is solved. It is solved because you redo the same fix than me here : https://github.com/iBotPeaches/Apktool/commit/e723e6e68f9b119b3a2fb07067aae648d8070718#diff-3ecc3b60f827748c316d780fc358139f .

**Pull request closed without merging**
