### PR TITLE
update url of Google Code to GitHub

### PR DESCRIPTION
**Pull request by CzBiX**

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Looks like an update to `https` in most places in addition to simply changing URL from Googlecode -> Github.

nast

Maybe that is isolated to me, but can't seem to load the maintained image now. Will investigate.

**Comment by CzBiX** [comment]
I'm not sure what's wrong, but I can't view this image too at right now . I will split off commit and test image URL later.

**Comment by CzBiX** [comment]
I found the reason, the site has config SSL cert incorrectly. It's only provide one cert without the chain.
I will try to contact with the site owner to fix it. But this PR should be acceptable for merge right now.

**Comment by iBotPeaches** [comment]
Thanks for investigation that! Merged in the other changes.

**Pull request merged**
