### PR TITLE
[WIP] Support for AndroResGuard v1.2.11

### LINKED ISSUE #1719: decompiling latest Facebook APK - unsupported res type name for bags. Found: style2
### Information
1. **Apktool Version: 2.3.1**
2. **Operating System: Linux**
3. **APK From: APKMirror (https://www.apkmirror.com/apk/facebook-2/facebook/facebook-157-0-0-38-97-release/facebook-157-0-0-38-97-android-apk-download/)**

### Stacktrace/Logcat

```
Very long sequence of "Could not decode file" lines: 
```
https://pastebin.com/edit/rHKMqygQ

### Steps to Reproduce
1. Any attempt to decompile the official Facebook apk (versions 157 and later)
2. ./apktool d _in/Facebook_157.0.0.38.97.apk -o _working/Facebook_157.0.0.38.97.apk 

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG): **Nope**

### APK
If this APK can be freely shared, please upload/attach a link to it: https://www.apkmirror.com/apk/facebook-2/facebook/facebook-157-0-0-38-97-release/facebook-157-0-0-38-97-android-apk-download/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? **yes**
2. If you are trying to install a modified apk, did you resign it? **issues during decompile/recompile**
3. Are you using the latest apktool version? **yes**

### PR DESCRIPTION
**Pull request by iBotPeaches**
fixes #1719 

 - [ ] add tests
 - [ ] add fix for unknown directory names (must remap back to regular)

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Lets split our these commits and merge it:

d930069bf968dbe973ee1bae73ad8827206efdd7
fd6eeba0a17984e969528e7f847fb4f7a1f867c5

The other commits need more investigation due to the type mess

**Comment by iBotPeaches** [comment]
My pull-request. Did not work and hacky as shit. Closing

**Comment by Bnaya** [comment]
What dose it means?

**Comment by iBotPeaches** [comment]
What does what mean @Bnaya ?

**Comment by Bnaya** [comment]
Will we have androres guard support?😅

**Pull request closed without merging**
