### PR TITLE
fix recordUncompressedFiles Method bug.

### PR DESCRIPTION
**Pull request by realityJie**
there files should not be compressed:
1.base on AOSP's frameworks/base/tools/aapt/Package.cpp: NO_COMPRESS_PATTERN = Pattern.compile("(jpg|jpeg|png|gif|wav|mp2|mp3|ogg|aac|mpg|mpeg|mid|midi|smf|jet|rtttl|imy|xmf|mp4|" +
            "m4a|m4v|3gp|3gpp|3g2|3gpp2|amr|awb|wma|wmv|webm|mkv)$"); specifically this rule include 9patch files.
2.file has not ext
3.the compressive type is store

**warning:
even if there are the same type of files, they are compressive type may different, just like this example:**
-rw----     1.0 fat     8343 b-  0% stor 80-Jan-01 08:00 assets/resources/assets/effect/common/ctp_trail15_1_tex.unity3d
-rw----     1.0 fat    11526 b-  0% stor 80-Jan-01 08:00 assets/resources/assets/effect/common/ctp_trail15_tex.unity3d
-rw----     2.0 fat     2483 bl 19% defN 80-Jan-01 08:00 assets/resources/assets/effect/common/cw_310300_cylq_ql01_mat.unity3d
-rw----     2.0 fat     9467 bl 17% defN 80-Jan-01 08:00 assets/resources/assets/effect/common/cw_310300_cylq_ql03_fbx.unity3d
ctp_trail15_1_tex.unity3d and ctp_trail15_tex.unity3d are uncompressed, but cw_310300_cylq_ql01_mat.unity3d and cw_310300_cylq_ql03_fbx.unity3d are compressed.

That is why I modified recordUncompressedFiles Method.

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Hi! Thanks for the PR, but there are a lot of changes here outside of the original modification. Anyway to fix this to just the change? Would make it easier to review.

**Comment by realityJie** [comment]
> Hi! Thanks for the PR, but there are a lot of changes here outside of the original modification. Anyway to fix this to just the change? Would make it easier to review.

I am so sory, I just use `ctrl+alt+l` to format the code.  The primary change is the `recordUncompressedFiles ` method.

**Comment by realityJie** [comment]
Hi, Connor.  I have update Androlib.java.

**Comment by iBotPeaches** [comment]
Looks good in terms of syntax now. I'm just not sure we can merge this. Unity has been our real pain point of same extension files differing between STORED/PACKED. With this change, we've ripped out the portion of code that records full paths of assets.

We have another change related to this ongoing at https://github.com/iBotPeaches/Apktool/pull/2192, so might have to watch that one first.

**Comment by realityJie** [comment]
> Looks good in terms of syntax now. I'm just not sure we can merge this. Unity has been our real pain point of same extension files differing between STORED/PACKED. With this change, we've ripped out the portion of code that records full paths of assets.
> 
> We have another change related to this ongoing at #2192, so might have to watch that one first.

Okey，no problem~

**Comment by realityJie** [comment]
reopen in #2227

**Pull request closed without merging**
