### PR TITLE
 Not possible to decode resources while decompiling Facebook lasted APK

### PR DESCRIPTION
**Pull request by ldavidsp**

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Not sure I'm a fan of this patch. Are `style2/3/4/5/6` real resource types? Or just fabricated and created by Facebook? Could it go up to 10? 20? 100? I think we need to properly research this, but thanks for the start!

**Comment by bkaankose** [comment]
It can go more then 3-4-5... I am currently dealing with an apk that has style12 resources as well and the interesting part is, you can't assume they are normal style resources. No matter how many handlers you add for style[number], it will not compile properly.

I'm not sure which problem this PR actually fixes.

**Comment by iBotPeaches** [comment]
Sorry meant to close this yesterday. I don't think this is the correct method to resolve this issue, but I thank you for making an attempt.

**Comment by ldavidsp** [comment]
Review PR https://github.com/iBotPeaches/Apktool/pull/2293

**Comment by ldavidsp** [comment]
He had not had time to review this until today. 
image

**Pull request closed without merging**
