### PR TITLE
build: add latest linux/windows aapt|aapt2 binaries

### PR DESCRIPTION
**Pull request by iBotPeaches**
Fixes: #2386

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Rebuilt linux/windows. Off to figure out mac build issues.

**Comment by iBotPeaches** [comment]
This is getting annoying.

```
RPC failed: HTTP 499 curl 16 Error in HTTP2 framing layer
```

I can't pull down code to even build AOSP. I thought it would temporary, but its been months now.

**Comment by MrIkso** [comment]
@iBotPeaches maybe more large files
https://stackoverflow.com/questions/61779275/git-push-hangs-up-unexpectedly-rpc-failed-error-in-http2-framing-layer

**Comment by iBotPeaches** [comment]
> @iBotPeaches maybe more large files
> https://stackoverflow.com/questions/61779275/git-push-hangs-up-unexpectedly-rpc-failed-error-in-http2-framing-layer

Its strange, because I didn't think AOSP used any git-lfs yet and I'm not even trying to push anything, just literally pull down the source. I can pull the same exact source on Ubuntu, so my guess is I'm missing some configuration on mac that is breaking something.

**Comment by MrIkso** [comment]
@iBotPeaches  as an option, clone the required repositories in parts. I did so when compiling the version for android

**Comment by luchitor** [comment]
ttr

**Comment by mkilling** [comment]
I think it would be amazing to automate the AAPT1/AAPT2 builds with Github Actions, but from quickly skimming the docs the Github runners only provide 14GB of disk space and will probably not be able to handle that 250GB AOSP repo...

**Comment by iBotPeaches** [comment]
> I think it would be amazing to automate the AAPT1/AAPT2 builds with Github Actions, but from quickly skimming the docs the Github runners only provide 14GB of disk space and will probably not be able to handle that 250GB AOSP repo...

Yeah I explored that during the switch from Travis. The partial build outs of AOSP, where you only have the repos related, may work within those limits, but its a never ending battle to keep those up to par and building with every change.

**Pull request merged**
