### PR TITLE
fix: redesign StyledString decoding

### LINKED ISSUE #2815: [BUG] Incorrect order of HTML tags in strings
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.X
2. **Operating System (Mac, Linux, Windows)** - Any
3. **APK From? (Playstore, ROM, Other)** - Dummy

### Description
apktool 2.6.X messes up the order of HTML tags in strings when decompiling an APK, rendering it impossible to recompile without manually fixing the broken tags, like Android 11's Settings.apk (AOSP) with full translations.
`<br/><br/>` decompiled as `<br></br><br></br>` with 2.5.1 but `<br><br></br></br>` with 2.6.X
`</b><br/>` decompiled as `</b><br></br>` with 2.5.1 but `</br></b><br>` with 2.6.X
... and so on. Full example:

Original string:
`<string name="test">Quickly zoom in on the screen to display content more clearly.<br/><br/> <b>To zoom in:</b><br/> 1. Use shortcut to start magnification<br/> 2. Tap the screen<br/> 3. Drag 2 fingers to move around screen<br/> 4. Pinch with 2 fingers to adjust zoom<br/> 5. Use shortcut to stop magnification<br/><br/> <b>To zoom in temporarily:</b><br/> 1. Use shortcut to start magnification<br/> 2. Touch &amp; hold anywhere on the screen<br/> 3. Drag finger to move around screen<br/> 4. Lift finger to stop magnification</string>`
Decompiled with apktool 2.5.1:
`<string name="test">Quickly zoom in on the screen to display content more clearly.<br></br><br></br> <b>To zoom in:</b><br></br> 1. Use shortcut to start magnification<br></br> 2. Tap the screen<br></br> 3. Drag 2 fingers to move around screen<br></br> 4. Pinch with 2 fingers to adjust zoom<br></br> 5. Use shortcut to stop magnification<br></br><br></br> <b>To zoom in temporarily:</b><br></br> 1. Use shortcut to start magnification<br></br> 2. Touch &amp; hold anywhere on the screen<br></br> 3. Drag finger to move around screen<br></br> 4. Lift finger to stop magnification</string>`
Decompiled with apktool 2.6.X:
`<string name="test">Quickly zoom in on the screen to display content more clearly.<br><br></br></br> <b>To zoom in:</br></b><br> 1. Use shortcut to start magnification<br></br> 2. Tap the screen<br></br> 3. Drag 2 fingers to move around screen<br></br> 4. Pinch with 2 fingers to adjust zoom<br></br> 5. Use shortcut to stop magnification<br><br></br></br> <b>To zoom in temporarily:</b><br></br> 1. Use shortcut to start magnification<br></br> 2. Touch &amp; hold anywhere on the screen<br></br> 3. Drag finger to move around screen<br></br> 4. Lift finger to stop magnification</string>`

### Steps to Reproduce
Simply compile the source with `apktool b`, then decompile the output APK with `apktool d`.

### APK
Source for a minimal dummy APK uploaded here:
https://drive.google.com/file/d/1wZKVpsHRuOxV9Fdnj3iYovPyfpcoQ2t2/view?usp=sharing

### PR DESCRIPTION
**Pull request by IgorEisberg**
Fixes #2815 by using recursive writing of nested tags instead of relying on questionable sorting methods.

### CODE REVIEW

**Comment by IgorEisberg** [comment]
Somewhat inspired by this:
https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:resource-repository/main/java/com/android/resources/aar/ProtoStyledStringDecoder.java;l=28?q=StyledString

But using recursion allows for cleaner code and easy handling of self-closing tags which neatly outputs pairs like `<br></br>` as `<br/>` which is the XHTML standard.

**Comment by iBotPeaches** [comment]
Interesting the only test failing in Isolation in some setups is the test that was added that led to these regressions.

Thanks for PR. Slowly going through w/ debugger to understand.

**Comment by IgorEisberg** [comment]
Yeah I'm not sure what's going on with that test, tried compiling/decompiling with all of the strings in that XML and the output was identical, both with aapt1 and aapt2. Very strange.

**Comment by IgorEisberg** [comment]
Looks like an issue with aapt1. When the APK is compiled with it, spans are not stored in the same order as with aapt2.
So for string:
`<string name="test_string43"><ul> <li><b>aaaaa aa aaaaa</b> – aaaaaaa aaaaaaaaaa aa aaaaaaaa aaaaaa aaaaa (aaaa) aaaa aaaaaaaaa aaaaa aa aaaaaaaaa aaaaaaa aaaa</li> <li><b>aaaaaaaaa aaaaaaaaaaaaaaa aaaaaaaa</b> – aaaaaaa aaaaaaaaaa aaaaaaaaa aaaa aaaaaa aa aaaa aaaa aaaa aaaa aaaaaaa aaaaaaaaaaaaa, aaaaaa aaa aaaaaaaaaa (aaa) aaaaaaaaaaaaaaa</li> <li><b>aaaaaaaaaaa aaaaaa aaaaaaaaaa</b> – aaaaaaaaaa aaaa aaaaaa aa a aaa aa aaaaaa aaa aaaaaaa (aaaaa aaaaaaaa) aaaaaaaa aa aaaaaa aaaaa aaa aaaa</li> </ul></string>`

Spans when compiled with AAPT1:
```
0: b (1-15)
1: li (1-115)
2: b (116-150)
3: li (116-283)
4: b (284-313)
5: li (284-420)
6: ul (0-421)
```

Spans when compiled with AAPT2:
```
0: ul (0-421)
1: li (1-115)
2: b (1-15)
3: li (116-283)
4: b (116-150)
5: li (284-420)
6: b (284-313)
```

**Comment by IgorEisberg** [comment]
Due to the above span ordering discrepancy between aapt1/2 I had to write a simple sorting function.
Would be more robust if we could somehow detect which aapt was used to build a given resources.arsc, but this is serviceable for most cases, although cases like:
`... </li><br/><br/><li><b>Title</b> ...`
Would decompile to something like:
`... </li><li><b><br/><br/>Title</b> ...`
It's an unusual case though...

**Comment by iBotPeaches** [comment]
Thanks for the large investigation and fix. Will try and visit again tomorrow to step through it as well for my own understanding.

**Comment by IgorEisberg** [comment]
By the way, I tried with Google's own ProtoStyledStringDecoder, and it also just handles AAPT2's spans (ordered by opening tag?) properly, while AAPT1's spans (ordered by closing tag?) are heavily misplaced. I don't even know of a single piece of code that decodes AAPT1's spans properly, let alone code that supports both orderings...

**Comment by iBotPeaches** [comment]
My guess is Google can just always depend on aapt2 in Studio prior to bundletool being used. I think every month we see less and less applications being disassembled via aapt1. Of course ignoring legacy apps.

**Review by iBotPeaches — APPROVED** [review]

**Pull request merged**
