### PR TITLE
Adding new option. Keep META-INF directory

### PR DESCRIPTION
**Pull request by pjakubczyk**
A very similar method to "copy-original".
Just copies the META-INF directory. I found an application which used this directory during application runtime. Next to standard results from jarsigner they are storing other kind of signatures.

I've named params "--keep-meta" and "-k" but it up to you @iBotPeaches to choose :)

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Thanks for the PR!

Lately the `--copy-original` function has lost its purpose as newer Android versions don't seem to accept it. In the early days you could decode, rebuild with `-c` and reinstall said application. These days you will get invalid certificate/manifest errors forcing you to resign the application from scratch.

If anything, I would merge these changes into the existing `--copy-original` function as it doesn't make much sense to split these up.

**Comment by pjakubczyk** [comment]
Thanks for a short history lesson :) I'll apply your suggestion over the weekend. Hear you soon.

**Comment by pjakubczyk** [comment]
The main difference is that Manifest is not included. You're sure to change the functionality of this option? If so you're ready to make an non-backward compatibility change ;)

**Comment by iBotPeaches** [comment]
Ah I misunderstood. For some reason I thought `-c` just copied `AndroidManifest.xml`. I don't see the real purpose of this with just `META-INF`.

The binding of signatures was only applied on the `AndroidManifest.xml`, thus generating the `META-INF` files. So this feature allowed you to change every other file, BUT `AndroidManifest.xml` and use the original `META-INF` and `AndroidManifest.xml` and you could install the apk without explicitly resigning.

This of course as mentioned above has changed with the release of API 20, so is entirely useless, which is why I even debated about removing the feature completely.

Can you let me know the usecase why you need the original `META-INF` but not original `AndroidManifest.xml`? If an application stores unknown files in the `META-INF` directory, that might be difficult to add support for as a whitelist of signature related files would have to be made to differentiate those files vs unknown ones.

**Comment by pjakubczyk** [comment]
Let's focus only on `META-INF`. There is possibility to pack some additional files to this directory and during runtime the process can read configuration/other certificate.  Unfortunately I can't share name of this application :( 

As far I know a developer can place additional files in `META-INF` directory after the apk has been signed without breaking the seal. It concludes that you could use `JarFile.getEntry("META-INF/secret_file.json")` during runtime.

I'm just thinking that if something isn't illegal it means it's legal  :)

**Comment by iBotPeaches** [comment]
True, but then we have an additional parameter that is basically `-c` minus the `AndroidManifest.xml`. Seems a bit weird. Let me think of some ideas. In the past for some parameters, we added long parameters only like `--line-ending` so maybe this option can be a long option on the existing `-c`. I need to brainstorm.

**Comment by pjakubczyk** [comment]
A long options sounds fine to me since it's not that frequent switch

**Comment by pjakubczyk** [comment]
@iBotPeaches the conversation got a bit stale :) do we agree to have only `--keep-meta` long option?

**Comment by iBotPeaches** [comment]
Can you let me know why you need need `META-INF` but not `AndroidManifest.xml`? Is there any harm with using an existing command vs adding in another parameter for such an edge case.

If we went forward, it would be `--skip-manifest` hooked onto the existing `-c / --copy-original` command, which would skip the copying of `AndroidManifest.xml`, thus only keeping the `META-INF` folder.

**Comment by pjakubczyk** [comment]
I wrote the reason in this comment https://github.com/iBotPeaches/Apktool/pull/1231#issuecomment-215396496

The whole idea behind it is to allow developer to do such option. It's more flexible this way. From my perspective it doesn't matter I should use `--keep-meta` alone or `--skip-manifest` combined with `-c` once it's documented.

**Comment by iBotPeaches** [comment]
I'm sorry then I don't see a need for an additional parameter. `-c` already works with the entire `META-INF` folder and `AndroidManifest.xml` file. I was simply asking why you don't want the `AndroidManifest.xml` file. The use case is still unknown. You've made it clear there are additional files in `META-INF` and according to my tests those are contained.

If there is some reason you require the `META-INF` folder, but NOT the `AndroidManifest.xml` file, I recommend adjusting your scripts to simply remove the `AndroidManifest.xml` file from the `original` folder after decode. Bloating parameters and commands is a real concern of mine because it leads to a CLI output that looks like a nightmare.

**Comment by pjakubczyk** [comment]
Because my script decompile an application and **modifies** the `AndroidManifest.xml` therefore I must skip coping the original Manifest but copy `META-INF` :)

**Comment by wahajs00** [comment]
hey is this the reason why get error with recompiling systemui.apk with -c ??
@iBotPeaches

**Comment by lbdroid** [comment]
"The binding of signatures was only applied on the AndroidManifest.xml, thus generating the META-INF files. So this feature allowed you to change every other file, BUT AndroidManifest.xml and use the original META-INF and AndroidManifest.xml and you could install the apk without explicitly resigning.

This of course as mentioned above has changed with the release of API 20, so is entirely useless, which is why I even debated about removing the feature completely."

Note that there is a difference in the handling of signatures when it comes to user applications (/data/app), system applications (/system/app), and *privileged* system applications (/system/priv-app). If you're working with system or privileged system applications, then this still works up to at least API23.

**Comment by iBotPeaches** [comment]
Yeah I apologize on this. I should have closed this years ago. I either didn't fully understand or agree with this change so did not want to move forward with it. I am looking forward to treating all future pull requests in 2019 with more timely care and not letting this staleness happen again.

For that again, I apologize for the long delay for closing a merge.

**Comment by BLuFeNiX** [comment]
@iBotPeaches I propose we re-open this (or make a new ticket). I am facing an issue where I want to keep META-INF files (not related to the APK signature, but used for storing some assets), and also change the package name via `apktool.yml`'s `renameManifestPackage`.

It seems this cannot be done because using `-c` with `apktool b` will not honor the `renameManifestPackage` changes. The package name remains the same.

**Pull request closed without merging**
