### PR TITLE
Fix: numeric string meta-data value corruption

### PR DESCRIPTION
**Pull request by codylund**
Addresses #2611.

### CODE REVIEW

**Comment by codylund** [comment]
As pointed out by a team member, it seems the >= 9 length was intentionally added in f3e21023ac25a09e662aa876cd0a62db34e4e5a4. Will adjust the regex to be `(\\s\\d+|\\d{9,})`

**Comment by iBotPeaches** [comment]
Thanks. Leaving a note to let you know I've seen this, but a bit busy this week. Will make sure I take a serious look before I cut 2.5.1 to include/leave feedback.

I've allowed the CI suite to run.

**Review by iBotPeaches — CHANGES_REQUESTED** [review]
Do you mind adjusting the test file here to help give some context to this change? We have 4 test entries, but I'm struggling to figure out what additional changes I could add there that help automate that this portion does not regress.

https://github.com/iBotPeaches/Apktool/blob/master/brut.apktool/apktool-lib/src/test/resources/aapt1/testapp/res/layout/issue1130.xml

**Comment by codylund** [comment]
Taking a deeper look into the issue 1130 tests, I noticed that aapt does not cast arbitrary numeric resource string values to non-string values. This inferred casting only appears to occur for manifest meta-data values. In issue1130.xml, compiling large ints without the escaped whitespace does not produce unexpected values or types for either aapt1 or aapt2. The are encoded as strings without needing to prepend an escaped space.

Perhaps we should instead be patching StaticXmlSerializerWrapper to detect `meta-data` elements and fix-up the numeric string resource values there. Thoughts @iBotPeaches?

**Comment by codylund** [comment]
Based on the find in my last comment, I've reworked the solution a bit. The change is now significantly scoped and should only apply to numeric string meta-data values in AndroidManifest.xml.

**Review by iBotPeaches — APPROVED** [review]

**Comment by iBotPeaches** [comment]
thanks!

**Comment by itaybia** [comment]
i believe the changes in brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResStringValue.java
related to the addition of "\ " should be removed.
as mentioned by @codylund, the changes by aapt seem to happen only for the metadata, and not other xml values.

**Pull request merged**
