### PR TITLE
Add option to force decoding of AndroidManifest.xml

### PR DESCRIPTION
**Pull request by rubenanagua**
Forces decoding of AndroidManifest.xml, even if `--no-res` is set. This is useful for analysis of the manifest if resources aren't relevant, saving the step of decoding other resources, which account for a significant amount of time.

I have set it to be an advanced option, named `--force-manifest` (feel free to change this). As such:
- Setting `--force-manifest` and not setting `--no-res` does not change the previous behavior of Apktool;
- Setting `--force-manifest` and `--no-res` decodes AndroidManifest.xml, but not other resources.

If accepted, I can submit another pull request regarding `gh-pages` with documentation for this option.

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Thanks for this. I am going to do a few tests and perhaps add a test suite to prevent regression and I'll get this merged.

**Comment by iBotPeaches** [comment]
Thanks again! Worked great and added a few tests to prevent regressions. 

The docs repo needs a slight update for new parameters, but the local spin up of docs (or mine) is having some troubles. So no worries on updating docs. I'll get those added when I get docs working locally again.

**Comment by 0x454447415244** [comment]
Is it possible to recompile if we set both flags --force-manifest and --no-res ? I tried it but it doesn't work. The manifest file will be considered as corrupted and the package won't install.

The thing is that I need to perform some changes to the manifest file without decompiling the resources (which is problematic most of the times), then rebuild the package.

It seems that the build feature does not recompile the manifest file when --no-res flag was used during unpack. The manifest file will be in ascii form after recompile.

Any solution? Thanks.

**Comment by z3r0Sec** [comment]
Same problem as 0x454447415244
I need to perform some changes to the androidmanifest.
but it stays decoded when using --force-manifest and --no-res after recompiling

**Pull request merged**
