### PR TITLE
Feat: Disable auto generation dummy attributes

### LINKED ISSUE #2462: [BUG]
### Information
Apktool 2.5.1-145201-SNAPSHOT

### Stacktrace/Logcat

```
Include stacktrace here
I: Using Apktool 2.5.1-145201-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'wfcSpnFormat' has no default translation.
W: Failed to generate resource table for split ''
W: C:\Users\Sac23\Desktop\hhh\framework-res\res\values\integers.xml:361: error: Error: String types not allowed (at 'APKTOOL_DUMMY_72' with value '').
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Sac23\AppData\Local\Temp\brut_util_Jar_64426037738495893106265858736697657594.tmp, p, --forced-package-id, 1, --min-sdk-version, 29, --target-sdk-version, 29, --version-code, 29, --version-name, 10, --no-version-vectors, -F, C:\Users\Sac23\AppData\Local\Temp\APKTOOL9077465573776423434.tmp, -x, -e, C:\Users\Sac23\AppData\Local\Temp\APKTOOL5862047175049083314.tmp, -0, arsc, -S, C:\Users\Sac23\Desktop\hhh\framework-res\res, -M, C:\Users\Sac23\Desktop\hhh\framework-res\AndroidManifest.xml]
```

### Steps to Reproduce
1. `apktool `

### Frameworks
samsung framework-res,apk

### APK

[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/5642054/framework-res.zip)

### Questions to ask before submission
im having issues repacking res it gives issues with apktool_dummy
in integers.xml and dimens.xml

### PR DESCRIPTION
**Pull request by MrIkso**
As for me, they are not needed and the code will be cleaner. Therefore, in the morning I decided to make this feature. Also will partially fix #2462.

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Thanks - I need to think about this. This is effectively destroys recompilation and leaves you without a non-working app. So I want to weigh things in my head.

**Comment by MrIkso** [comment]
Well, in theory, everything may not work, but in practice I have not noticed any problems yet. Check on some apps.

**Comment by iBotPeaches** [comment]
I'm leaning in a direction to not merge this, because dummy attributes are required in circumstance where the res type spec is destroyed, but yet the resource is referenced. So I'm curious what your use-case/background is for this? 

(outside of like making it look cleaner)

**Comment by MrIkso** [comment]
Hi, dummy does not restore anything in the resource structure, only one garbage from which the apk can't be builded.  The new dummy attribute format is no can't used by aapt, so the support with aapt2 has been fixed.  It turns out that they fixed it in one place, and broke it in another.  I am attaching to the user the ability to disable these problematic attributes.

**Comment by AndnixSH** [comment]
I really need this option. I always have to remove dummys manually in order to compile, and they are working fine so far.

**Review by aleee1333 — APPROVED** [review]

**Review by aleee1333 — APPROVED** [review]

**Comment by leao-nardo** [comment]
as an [option] this seems interesting . dont need to be the default , the person can just add it when wanted like --no-dummys . seems a good thing to be added to automate that step when its desired.
because doing it manually seems repetitive and time consuming.
maybe later if most people start using and most tools compile that better than i can be made default.

**Review by tuanvu2605 — APPROVED** [review]

**Comment by iBotPeaches** [comment]
I took a look at this again and nothing specific to this PR, but our method of loading configurations into the disassembly side is horrible. Its either class variables at the AndroLibResources, AndroLib, ArscDecoder, ResTable level. The `ApkOptions` I introduced for building might be a good cleanup/refactor here. Would get to clean up all the various get/sets that are used solely to pass context around.

Came to my mind when I saw a new value having to be added to a bunch of functions. etc

**Pull request closed without merging**
