### PR TITLE
Ensure Newlines at Ends-of-Files

### PR DESCRIPTION
**Pull request by ankitpati**
Majority of the source files have a newline at EOF, but a significant minority do not.

This PR should help with the [“Be consistent” principle](https://source.android.com/setup/contribute/code-style#be-consistent "AOSP Code Style").

### CODE REVIEW

**Comment by iBotPeaches** [comment]
I'm going to have to do some tests with this one. Changing `LICENSE` is used in automatic formatting so not sure if that will have any negative side affects.

**Comment by ankitpati** [comment]
I built it, ran the test suite successfully, and tested it out on a couple of APKs. Seems to work fine.

Can you please explain that part about `LICENSE`? I didn’t quite get it.

**Comment by iBotPeaches** [comment]
> Can you please explain that part about `LICENSE`? I didn’t quite get it.

We have some commands that set licenses on files.

```
./gradlew licenseFormatMain
./gradlew licenseFormatTest
```

It knows what license to add based from that file, but since you added a newline - will this command add newlines to every file?

**Comment by iBotPeaches** [comment]
Thanks, but not going to go forward with this one. I don't really want to spam a commit to add missing newlines especially when I don't have anything to enforce it at this time. The next time I look into automation for cs - I'll visit this.

**Pull request closed without merging**
