### PR TITLE
Code cleanups

### PR DESCRIPTION
**Pull request by Goooler**

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Are you working on this more @Goooler ? Or may I slip in some commits and merge this?

**Comment by Goooler** [comment]
> Are you working on this more @Goooler ? Or may I slip in some commits and merge this?

Ok, thanks.

**Comment by iBotPeaches** [comment]
Couldn't push to this. Opening up: https://github.com/iBotPeaches/Apktool/pull/2645, closing this one.

**Comment by Goooler** [comment]
Ok.

**Pull request closed without merging**
