### PR TITLE
merge

### PR DESCRIPTION
**Pull request by pwelyn**
Updated to Gradle 2.3
Updated to ProGuard 5.2 to handle java8

### CODE REVIEW

**Comment by pwelyn** [comment]
Updated to Gradle 2.3
Updated to ProGuard 5.2 to handle java8

**Comment by iBotPeaches** [comment]
Creepy timing. I had already updated Proguard to 5.2 about 7 hour before you :)

https://github.com/iBotPeaches/Apktool/pull/102

I don't want to update to Gradle 2.3 yet, unless its fixing a bug.

**Comment by pwelyn** [comment]
brut.apktool.smali / build.gradle not updated Proguard to 5.2

**Comment by iBotPeaches** [comment]
nice catch. I'll get on that.

**Pull request closed without merging**
