### PR TITLE
Fixes issue #402: java.lang.NullPointerException when apktool runs as a system user

### PR DESCRIPTION
**Pull request by rscarvalho**
The reference issue is https://code.google.com/p/android-apktool/issues/detail?id=402

### CODE REVIEW

**Comment by iBotPeaches** [comment]
While this fixes the issue at hand which you mentioned, I'm concerned with saving frameworks to `java.io.tmpdir`. Frameworks aren't meant to be temporary files, they are suppose to be organized among  lots of others spread across different OEMs and Android versions.

The instant we start writing them to `/tmp`, we have no idea if there existence will stay or not or for how long. This could lead to a fragmented experience where users install frameworks, loose them via `/tmp` clearing and then wonder why decoding/building isn't working. 

Now obviously, storing the file in `/tmp` because its original directory cannot be written makes sense, but the user has no idea this happening. I might merge this if I add some annoying output messages like.

"Could not write to _____, using _____ instead."
"Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable (`$HOME/apktool/framework`)

Then again, thats a lot of information to write out. Especially if the user is knowingly utilizing this change. I need to think about it. 

Thanks for bringing it up though and starting a PR.

**Comment by rscarvalho** [comment]
@iBotPeaches yes sure. I think if we issue a warning on the command-line like you mentioned above is fine. I can augment the PR to include a warning message whenever this edge case happens.

Ultimately if this is a "let it crash" scenario, at least we should throw a `AndroidlibException` to we actually see an error message in the command line.

**Comment by raziel23x** [comment]
or could it also be that forcing the use of admin rights for windows could also fix the write access issue?

**Comment by rscarvalho** [comment]
@raziel23x I don't think this is the best approach. Also, this issue is happening with me on a linux box, where running processes with unprivileged user is a very common (and encouraged) practice.

**Comment by iBotPeaches** [comment]
https://github.com/iBotPeaches/Apktool/commit/f089edd2d6926301bd0175818277bcb6ce2f5e6f

Thanks!

**Pull request closed without merging**
