### PR TITLE
Consistently encode unknown filenames to prevent cast error

### PR DESCRIPTION
**Pull request by ihanson**
This pull request fixes an issue where an error could occur when building an APK file. Some APK files, when they are decoded and then built using Apktool, will cause the following error message:

```
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
Exception in thread "main" java.lang.ClassCastException: [B cannot be cast to java.lang.String
	at brut.androlib.Androlib.copyUnknownFiles(Androlib.java:635)
	at brut.androlib.Androlib.buildUnknownFiles(Androlib.java:600)
	at brut.androlib.Androlib.build(Androlib.java:307)
	at brut.androlib.Androlib.build(Androlib.java:268)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
```

The cause of the error message is this: when the SnakeYAML library encounters a `String` which contains non-printable characters while dumping an object to a file, the value is included in the resulting YAML file as a raw binary value instead of a string. When it reads this value in again, it stores it in a `byte[]` object instead of a `String`, which can cause problems if the code is expecting a `String`. The APK file with which I encountered this issue had files included in the `unknownFiles` object whose filenames contained non-printable characters.

This pull request fixes the issue by causing SnakeYAML to always encode the names of the unknown files as a byte array representing a UTF-8–encoded string, and decoding that string in the same way when loading the filename from `apktool.yml`.

An example of an app whose APK causes this issue is [MobilePass+](https://play.google.com/store/apps/details?id=com.gemalto.mobilepassplus).

### CODE REVIEW

**Comment by iBotPeaches** [comment]
I pulled that apk you linked to see the error at hand and didn't have a problem.

```
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1120$ apktool d MobilePASS_v1.0.6.6266_apkpure.com.apk 
I: Using Apktool 2.0.3 on MobilePASS_v1.0.6.6266_apkpure.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1120$ apktool b MobilePASS_v1.0.6.6266_apkpure.com
I: Using Apktool 2.0.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1120$ 
```

I like this change a lot though, because I know I've encountered it before. Would you mind adding some bogus test file to the root like `nonprintablechar.file` or something. So our unit tests can have a test for non-printable chars?

**Comment by ihanson** [comment]
Don’t merge this yet; the new test will fail in Windows.

**Comment by ihanson** [comment]
I’ve added a test file. The tests pass in both Linux and Windows.

**Comment by iBotPeaches** [comment]
Looks great. Thanks for doing everything perfect! Updating changelog now.

**Comment by iBotPeaches** [comment]
https://github.com/iBotPeaches/Apktool/commit/bfc4f97b355fd1f780192a9c4dc0d6ef375e1e98 Changelog updated

**Pull request merged**
