### PR TITLE
Code Cleanup (x2)

### PR DESCRIPTION
**Pull request by iBotPeaches**

### CODE REVIEW

**Comment by iBotPeaches** [comment]
thanks @Goooler !

**Comment by Goooler** [comment]
@iBotPeaches Found so many code format issues, like wrong `indent_style` and wrong `indent_size`, should be reformat once globally ?

**Comment by iBotPeaches** [comment]
> @iBotPeaches Found so many code format issues, like wrong `indent_style` and wrong `indent_size`, should we reformat once globally ?

I don't want to line style until there is an automated solution to enforce that same style for pull requests. Since I don't think its fair to enforce it, if there is nothing to confirm/check it.

**Comment by Goooler** [comment]
Seems there's only plugins to check style but not automated formating for PRs.

**Comment by Goooler** [comment]
If we should add a plugin to check style ?

**Pull request merged**
