### PR TITLE
Wires up rewriter of @string references in provider attrs

### LINKED ISSUE #636: references broken in AndroidManifest.xml due to public.xml
Original [issue 526](https://code.google.com/p/android-apktool/issues/detail?id=526) created by metsman83 on 2013-10-13T06:19:35.000Z:

 > <b>What steps will reproduce the problem?</b>
1.Decompile Google Keyboard APK
2.Recompile apk with or without changes.
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
Expected a recompiled usable apk, similar to when I run same commands to Android(Nexus) Keyboard. Instead I get tons of errors stateing cannot find res identifier.

<b>What version of the product are you using? On what operating system?</b>
1.5.2 and Windows 7 64bit

<b>Please provide any additional information below.</b>
This issue was touched on in topic #&nbsp;252. It is a somewhat old post and not extremly clear. I have tried doing what was suggested several times and cant get the command to work or the apk to recompile. The steps I took are:
1)apktool d com.google.android.inputmethod.latin-1.apk
2)changed package name in manifest to:&quot;com.android.inputmethod.latin&quot; (removing &quot;google&quot;)

FYI-Not sure if it matters but apktool.yml reads:
version: 1.5.2
apkFileName: com.google.android.inputmethod.latin-1.apk
isFrameworkApk: false
usesFramework:
  ids:
  - 1
sdkInfo:
  minSdkVersion: '14'
  targetSdkVersion: '17'
packageInfo:
  cur_package: android
  orig_package: com.google.android.inputmethod.latin
compressionType: false

3)I think this is where Im running into problems. I tried the following 3 commands:
apktool b com.google.android.inputmethod.latin --rename-manifest-package 

apktool b com.google.android.inputmethod.latin --rename w/ original_package

apktool b com.google.android.inputmethod.latin --rename w/ com.google.android.inputmethod.latin

Nothing seems to work. All it does is rename the file. Im pretty new to this and apoligize for the potentially stupid questions. If someone could help that would be amazing! Not sure if this fix is being worked into 2.0, I really hope so!

### PR DESCRIPTION
**Pull request by iBotPeaches**
- finds all <providers> in manifest
 - finds corresponding @string in res/values/strings.xml
 - does reference replacement w/ literal value
 - fixes #636

### CODE REVIEW

**Comment by iBotPeaches** [comment]
I've really messed up the purpose of `AndrolibResources` with all these XML tweaks that `aapt` requires. I'll move all these functions to a new class like `ResXmlPatcher` before I merge this. Still need to create unit-tests and test use-case with multiple providers in one manifest. (Is that even possible?)

**Comment by IaguCool** [comment]
Say, does your fix involves replacing reference IDs for hardcoded literals in AndroidManifest.xml? If so, this is an awful workaround, because it renders "Runtime Resource Overlay framework" useless...
http://developer.sonymobile.com/2014/04/22/sony-contributes-runtime-resource-overlay-framework-to-android-code-example/

**Comment by iBotPeaches** [comment]
The provider we are replacing reference for literal is for `ContentProviders`, not really related to the Resource Providers Sony talks about. This shouldn't affect that.

**Comment by IaguCool** [comment]
Yet, you do agree that references in ContentProviders should work, as they work in the original APKs. This is a great workaround, but it conceals the reason for recompiled APKs not working the same way.
Replacing values means 'the recompiled APK won't be the same as the original APK' and this should be only a temporary workaround until we find the issue behind this.

**Comment by iBotPeaches** [comment]
Trust me, this has been an open bug for almost 2 years. There is no other solution. The method we use to maintain consistent resource id's require us to use `public.xml` which obviously makes the resources public. For some strange bug, AOSP rejects any public `@string` reference in an authorities attribute in `AndroidManifest.xml`.

If we remove the `public.xml` change, then we'd have to rewrite all iterations of the resource ids among the application. Even with the most clever regex and introduction of dexlib2, this proved to be nearly impossible for all use cases. Newer iterations of `aapt` have been promising with `^attr-private` but not compatible with lower than lollipop hosts, so useless for Apktool to provide support for all versions.

Even finding the reason this bug exists in AOSP won't fix the bug already apparent in the rollout of jellybean, kikat and lollipop builds.

Your welcome to investigate the problem yourself, another set of eyes is always good. Working solo lends itself to mistakes, so maybe you'll find something I missed.

**Comment by IaguCool** [comment]
Seems like you've been diving into this issue for a long time now... I doubt I'll find anything you couldn't find yourself but I'll give it a try.

**Comment by IaguCool** [comment]
There's an issue: When recompiling for the first time, the provider-authorities gets replaced with the literal value, but when recompiling again, the literal gets deleted from the AndroidManifest.xml altogether, but should have just remained intact.

**Pull request merged**
