### PR TITLE
Determine minSdkVersion with baksmali for JARs + don't compress webp

### PR DESCRIPTION
**Pull request by IgorEisberg**
We take advantage of the fact that baksmali can determine the minimum API version needed for a given collection of opcodes and extract it, then save to mMinSdkVersion, which is only used by smali via buildSourcesSmali.
We then save that value in apktool.yml for JARs only.
This change, in addition to my previous change, allows to decompile and recompile JARs without worrying about specifying an API level via -api/--api-level.

Note: currently we only return API level from baksmali, later we can return a result object with other parameters, if ever necessary.

As an extra, added webp file extension to NO_COMPRESS_PATTERN, according to AAPT2 standards, and since it's factually never compressed as it's an already compressed format.
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/tools/aapt2/cmd/Link.cpp;l=2328

### CODE REVIEW

**Comment by iBotPeaches** [comment]
> We take advantage of the fact that baksmali can determine the minimum API version needed for a given collection of opcodes and extract it, then save to mMinSdkVersion, which is only used by smali via buildSourcesSmali.
> We then save that value in apktool.yml for JARs only.

Clever. So knowing we have no resources in a pure jar disassembling, you are basically using the opcode "detection" of baksmali to figure it out. At that point you can return the object from baksmali and extract the needed API code to write into what Apktool needs for the next step.

My only comment is now it seems `decode` returns an int, which is the API level from the decode. I'm not sure that is easy to follow just looking at the method. What do you think about returning the `dexFile` so that can be easily interpreted from the return type?

**Comment by IgorEisberg** [comment]
Yeah that was my first instinct, but then the nitpicky part of me said "encapsulation, bro". I was kinda hesitant importing anything from the org.jf.dexlib2.dexbacked package where it's not relevant, you know. I would rather keep the back-end stuff to SmaliDecoder and reveal only what's relevant to a multi-purpose class like Androlib, I would have used a class like "SmaliDecoderResult" to store stuff that needs to be revealed to the outside, but tell me what you prefer.

**Comment by iBotPeaches** [comment]
> Edit: Or even a public static class Result inside SmaliDecoder with public final int apiLevel in it and a single constuctor to be used and returned by decode, would be perfect for the task.

I like that idea, not sure on best location in file structure for intermediate result classes. Probably best for brut.androlib.meta where some other ones are.

**Comment by IgorEisberg** [comment]
Figured it'll be less clutter to return the dexFile, but as a simple DexFile interface rather than the back-end DexBackedDexFile implementation, as we're only interested in the getOpcodes method anyways, not the whole collection of methods that have nothing to offer to Apktool at the moment.

**Review by iBotPeaches — APPROVED** [review]

**Comment by iBotPeaches** [comment]
thanks!

**Pull request merged**
