### PR TITLE
refactor: ExtDataInput rework, source layout and formatting

### PR DESCRIPTION
**Pull request by IgorEisberg**
Refactor ExtDataInput classes: ExtDataInput is now the extended interface, ExtDataInputStream is an easy-to-use FilterInputStream implementing ExtDataInput with static creator methods for big-endian and little-endian wrappers.

Refactor AaptManager class: unify aapt-related verifications to one class.

Replace Apache Commons' deprecated CountingInputStream with Google Guava's equivalent with the same name. Apache's BoundedInputStream is an overkill for our use case and its constructors are deprecated as well.

Normalize source layout to have a common and somewhat more standard order: Static fields first, instance fields after, methods last.

Fix some formatting, like empty spaces or extra spaces and exception messages.

Renamed ResXmlPatcher to ResXmlUtils, as it has more purposes than just patching.

Renamed DirUtil to DirUtils, to match other utility classes naming convention.

Moved "properties/apktool.properties" to jar's root, to match smali/baksmali.

Moved Android Framework to "prebuilt", as it is just a prebuilt, looks out of place among .class files.

@SuppressWarnings removed from Duo as there are quite a few unsafe assignments of raw Duo[] instances to parameterized Duo<> variables in the project, this is just Java being the primitive boilerplate it is, no point in fighting it.

No end-user changes.
Tested against a full ROM decompile/recompile, no issues found.

### CODE REVIEW

**Comment by iBotPeaches** [comment]
117 changes :o

**Comment by IgorEisberg** [comment]
> 117 changes :o

Most of the changes are just lines moved around and some private variables renamed lmao

**Comment by 0xrxL** [comment]
Great work @IgorEisberg. I remember you from when you created Xiaomi EU ROMs 👍

**Comment by IgorEisberg** [comment]
> Great work @IgorEisberg. I remember you from when you created Xiaomi EU ROMs 👍

I'm still the only developer for Xiaomi.eu since 2017, besides the included Updater app.
Java ain't my cup of tea, but keeps me busy. I'd rather code C# all day than have to deal with that boilerplate of a language.

**Comment by iBotPeaches** [comment]
thanks!

**Pull request merged**
