### PR TITLE
Fix removal of META-INF/services folder (coroutines runtime exception fix)

### PR DESCRIPTION
**Pull request by adibfara**
Some libraries use the `META-INF/services` folder to store their service-locator-related files and these get removed automatically, since they are in the `META-INF` folder and assumed redundant. These libraries include Kotlin coroutines which use this folder to store service locator info for the main dispatcher and main exception handler implementation.
This can cause a `RuntimeException` whenever these libraries try to locate their services.

This PR tries to keep anything that is inside `META-INF/services` folder by copying it to the main APK folder like other normal folders. By doing this, this folder remains in the final APK and no run-time exceptions can occur.

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Thanks for the pr! I think we could easily add a test for this to ensure it doesn't regress and we need to fix up some of the spacing. Otherwise looks good. I can handle both of these in a few days if you don't want to.

**Comment by adibfara** [comment]
@iBotPeaches No problem! I actually added the unit tests, but you are more than welcome to add more.

I created a simple app that tries to make a coroutines call every 2 seconds using `Dispatchers.Main`. This app would crash using the older versions of APKTool (decode then encode), and does not using this version.

I added two unit tests, one for ensuring the `decode` part, which should contain the necessary files for coroutines (in `META-INF/services`) and one for the `build` part where the final apk should contain those files as well.

**Comment by iBotPeaches** [comment]
Thanks! Looks good. I'll have time later this week. If you have the source to that test app, you can push it here - https://github.com/iBotPeaches/TestApks

I keep that as a backup in case I need to rebuild apps in the test suite and for legality to make sure we aren't including copyrighted apks into test suite.

**Comment by adibfara** [comment]
[Done](https://github.com/iBotPeaches/TestApks/pull/3).

**Comment by iBotPeaches** [comment]
Thanks merged!

**Comment by adibfara** [comment]
Happy to help! :)

**Comment by peret** [comment]
This is awesome, thanks for fixing this! 👍
@iBotPeaches: Do you have a schedule in mind, when a new version including this fix will be released? 🙏

**Pull request merged**
