### PR TITLE
Workaround for string meta-data values that look like ints

### PR DESCRIPTION
**Pull request by gio73**
When a (manifest) meta-data value consists of digits only, then it is considered an int.
For instance, if the value of "answer" is "42", then the corresponding BaseBundle.getString("answer") returns null instead of "42" (while getInt() returns 42).
This fix/hack, of prefixing the value with "\\x3", makes sure that the value (in the newly generated AndroidManifest.xml) is considered a string nonetheless.

For an instance of this problem see: http://stackoverflow.com/questions/2154945/how-to-force-a-meta-data-value-to-type-string

Official documentation (somewhat vague):  http://developer.android.com/guide/topics/manifest/meta-data-element.html

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Thanks for the PR!

I need to do some research on the `meta-data` in manifest, write up some unit-tests then I'll take a look at this.

**Comment by gio73** [comment]
Thanks!

To see "in action" the problem that I'm trying to address, you can 
decode, then rebuild, for instance, the APK of the game Temple Run 2 
(http://apps.evozi.com/apk-downloader/?id=com.imangi.templerun2).

Decoding+rebuilding with standard Apktool makes the rebuilt APK crash at 
the startup, while the APK rebuilt with my workaround seems to work fine.
That said, I'm not sure if my workaround is in the right place of the 
code and/or if it is the smart thing to do :-)

**Comment by iBotPeaches** [comment]
Okay,

I made a ton of test apps using all the `gets` that `BaseBundle` had to offer and I found the weird problems. If you have an obvious integer, getString returns null. 

Prefix it, like shown here and getString & getInt return properly. However, does casting breaking anything else? Not in my testing. getString & getInt seemed to work with a prefix.

I will publish the test apps to the Test repo: https://github.com/iBotPeaches/TestApks soon and investigate whether this solution is proper.

**Comment by iBotPeaches** [comment]
Sorry for taking so long on this. I settled using `\\ ` and everything seems to working. Your precompiled regex was amazing in terms of profiling. Still running a few more profiling sessions to make sure this doesn't slow down anything, but thanks again.

I'll credit you in changelog and commits.

**Comment by iBotPeaches** [comment]
Superseeded by https://github.com/iBotPeaches/Apktool/commit/ba7393d705808f476982822ab22624b498fd8958

**Pull request closed without merging**
