### PR TITLE
Improve README link title

### PR DESCRIPTION
**Pull request by tutacat**

### CODE REVIEW

**Comment by iBotPeaches** [comment]
At the moment there is parity between the docs and tool header. This will break the parity - any reason you feel strongly the hyperlinked [here] is not sufficient?

**Comment by tutacat** [comment]
Did not realise that specifically, but theredoes not appear to be parity. README.md does not link to https://apktool.com, only docs header does. the "here" links to each other, but titles such as "here", "click here", and "this link" should not be used for links because a) they don't show what the link is for b) using a screen reader will often list the links on their own separately from the text, so the link title should match content and not rely on additional context.

**Comment by iBotPeaches** [comment]
Okay if you can PR the docs repo as well then (on branch `docs`) with the same change. I can merge both at once.

**Comment by tutacat** [comment]
Moved to #3611

**Pull request closed without merging**
