### PR TITLE
	Fix bug reencoding 9patch pngs

### PR DESCRIPTION
**Pull request by mattsarett**
Fixes issue 1180.
#1180

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Thanks for this. As I don't fully comprehend the inner workings of 9patch. Give me a bit to run a series of tests on images. Regressions in that past have images going darker/lighter on recompile so I don't want to run into that again.

**Comment by mattsarett** [comment]
Of course that makes sense.

The bug that I intended to fix was when the original png is encoded as a paletted image or as a gray image.  In that case, setRect() won't work because that call simply performs a memcpy().  What we really need to do is "draw" the original PNG into an RGBA output png.  The output PNG must be RGBA because of how we set the ninepatch border (and because it must "have alpha").

**Comment by iBotPeaches** [comment]
Sorry for the delay. I wrote a unit test to check basic properties of a 9 patch (the black border on decoded form, the 0,0 pixel and the middle part of image) to determine if

1) the 9patch data is retained
2) the color retains

https://github.com/iBotPeaches/Apktool/commit/fc43ec2470075c1652e4e66b72a13526acbfd5e2

**Comment by mattsarett** [comment]
Thanks a lot!

**Pull request merged**
