### PR TITLE
refactor: smali/baksmali in natural order

### PR DESCRIPTION
**Pull request by IgorEisberg**
Filters dex files (baksmali) and smali_* dirs (smali), then sorts them in natural order before processing them. (classes*.dex always come first, then non-standard paths)

Before:

I: Baksmaling classes.dex...
I: Baksmaling classes10.dex...
I: Baksmaling classes11.dex...
I: Baksmaling classes12.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Baksmaling classes6.dex...
I: Baksmaling classes7.dex...
I: Baksmaling classes8.dex...
I: Baksmaling classes9.dex...

I: Smaling smali folder into classes.dex...
I: Smaling smali_classes10 folder into classes10.dex...
I: Smaling smali_classes11 folder into classes11.dex...
I: Smaling smali_classes12 folder into classes12.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Smaling smali_classes3 folder into classes3.dex...
I: Smaling smali_classes4 folder into classes4.dex...
I: Smaling smali_classes5 folder into classes5.dex...
I: Smaling smali_classes6 folder into classes6.dex...
I: Smaling smali_classes7 folder into classes7.dex...
I: Smaling smali_classes8 folder into classes8.dex...
I: Smaling smali_classes9 folder into classes9.dex...

After:

I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Baksmaling classes6.dex...
I: Baksmaling classes7.dex...
I: Baksmaling classes8.dex...
I: Baksmaling classes9.dex...
I: Baksmaling classes10.dex...
I: Baksmaling classes11.dex...
I: Baksmaling classes12.dex...

I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Smaling smali_classes3 folder into classes3.dex...
I: Smaling smali_classes4 folder into classes4.dex...
I: Smaling smali_classes5 folder into classes5.dex...
I: Smaling smali_classes6 folder into classes6.dex...
I: Smaling smali_classes7 folder into classes7.dex...
I: Smaling smali_classes8 folder into classes8.dex...
I: Smaling smali_classes9 folder into classes9.dex...
I: Smaling smali_classes10 folder into classes10.dex...
I: Smaling smali_classes11 folder into classes11.dex...
I: Smaling smali_classes12 folder into classes12.dex...

### CODE REVIEW

**Comment by IgorEisberg** [comment]
For whatever reason "CI / Build/Test (JDK 10, ubuntu-latest)" failed. I'm unable to reproduce this using the same build command:
`./gradlew build shadowJar proguard`

**Review by iBotPeaches — CHANGES_REQUESTED** [review]
Right now I'm not feeling this as a needed improvement when we have to copy in an entire natural order class. Maybe if it was like part of Guava or something, but just didn't seem worth it for just changing the order we disassemble files.

**Comment by IgorEisberg** [comment]
Suit yourself.

**Comment by iBotPeaches** [comment]
It does seem like Guava has a natural sort - https://guava.dev/releases/23.0/api/docs/com/google/common/collect/Ordering.html#natural--

**Comment by IgorEisberg** [comment]
Misleading naming. In programming language sense "natural order" means "type-default order", i.e. as returned by the type's "compareTo" method. It's not the usual human-friendly "[natural sort order](https://en.wikipedia.org/wiki/Natural_sort_order)".
Just for demo, it says there "Java 8 users: use [Comparator.naturalOrder()](http://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html?is-external=true#naturalOrder--) instead.", and you can see how basic and underwhelming the implementation really is:
[Comparator.naturalOrder()](https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/java/util/Comparator.java#L342)
which simply gets an instance of...
[Comparators.NaturalOrderComparator](https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/java/util/Comparators.java#L42)

**Comment by IgorEisberg** [comment]
And same lame implementation in Guava's case, just calls compareTo.
http://www.javased.com/index.php?source_dir=platform_external_guava/src/com/google/common/collect/NaturalOrdering.java

**Comment by IgorEisberg** [comment]
I changed to a different (more recent) implementation of a natural order comparator that uses Apache 2.0 license like yours. If you ever change your mind, let me know and I'll do a fresh pull request. Meanwhile we're using this in our custom Apktool and I just figured pushing some generic stuff like this to official releases would minimize the changes we have to do when updating Apktool base version. Ultimately, it's up to you.

**Pull request closed without merging**
