### PR TITLE
test: add failing/passing sparse/not-sparse test

### PR DESCRIPTION
**Pull request by iBotPeaches**
This has a sparse packed and not application - https://github.com/iBotPeaches/TestApks/commit/a09e2ca86dc311ba35c08e408221ae596be36539

fixes: #3199

### CODE REVIEW

**Comment by iBotPeaches** [comment]
I'm confident in the tests here as they fail if I revert fix, but I'll leave this open for a few hours if you'd like to confirm @IgorEisberg

**Comment by IgorEisberg** [comment]
Works perfectly here, thanks for the quick patch.

**Comment by IgorEisberg** [comment]
One question regarding

```
            if (! mResTable.getSparseResources()) {
                mResTable.setSparseResources(true);
            }
```

Isn't the if check redundant? It's just setting a boolean, doesn't seem like making sure it's not set has much of a purpose.

**Comment by iBotPeaches** [comment]
> Isn't the if check redundant? It's just setting a boolean, doesn't seem like making sure it's not set has much of a purpose.

Yeah since that function has evolved to just a bool scalar set - it probably doesn't need that check anymore since its very cheap to do.

**Comment by IgorEisberg** [comment]
> 

Oh, I missed that piece of history. In any case, since I decompile/recompile whole ROMs I can confidently say that this was the last broken piece of the puzzle - can't find any other regressions. Neat release.

**Comment by iBotPeaches** [comment]
> Oh, I missed that piece of history. In any case, since I decompile/recompile whole ROMs I can confidently say that this was the last broken piece of the puzzle - can't find any other regressions. Neat release.

Yeah sorry about that, but I figured at some point I needed to rewrite some lower parts of code. I knew there was a chance of some regressions, but now I understand it far more than past and can iterate a bit quicker.

**Comment by IgorEisberg** [comment]
> Yeah sorry about that, but I figured at some point I needed to rewrite some lower parts of code. I knew there was a chance of some regressions, but now I understand it far more than past and can iterate a bit quicker.

All par for the course, that's how development goes. I actually use a flavor of Apktool that I customized especially for proper MIUI handling (including the Xiaomi-invented "nxhdpi" specifier), but always try to make a pull request for generic/non-MIUI fixes that others could use. ;)

**Pull request merged**
