### PR TITLE
update CLI commons API and optimize imports

### PR DESCRIPTION
**Pull request by xpirt**
this will just fix some warnings of deprecated API usage, I have noticed during compilation.

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Give this ticket a read - https://github.com/iBotPeaches/Apktool/issues/970

I'm worried about the DefaultParser as it doesn't work with my use case.

**Comment by xpirt** [comment]
Sorry, haven't noticed that.

While the initial issue (#970) is still present with the updated methods, all other options are still working for me (the ones without starting with `-` or `--` too, therefore also the next issues you faced). 
Not sure why it didn't for you.

If you want to test it, I've uploaded the newely compiled apktool here: 
[apktool-2.2.5-c6b2f2-SNAPSHOT-small.jar](https://drive.google.com/open?id=0BwmsIySoHg2FRXdITWd1akpFLVU)

As for the initial issue mentioned, I am going to fix it and reference it here in a few.

**Comment by xpirt** [comment]
It was very simple actually, harder to spot. You wrote at https://github.com/iBotPeaches/Apktool/blob/master/brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java#L417 line to loop for different group options and then add manually advanced options. 

You just forgot to add manually the `apiLevelOption` :)

**Comment by iBotPeaches** [comment]
Thanks! I'll take a closer here soon and see if everything was resolved.

**Pull request merged**
