### PR TITLE
Added support for PR builds on master

### PR DESCRIPTION
**Pull request by Fmstrat**
- Add docker JDK builder for PRs into main as a `:beta`
- ~~Replace `openjdk` with `sapmachine` as the original repo is deprecated, and sapmachine is official now~~
- Use `ibm-semeru-runtimes` (also official) for JDK/JRE 17 LTS

~~Held up by https://github.com/iBotPeaches/Apktool/issues/3362~~

### CODE REVIEW

**Review by iBotPeaches — COMMENTED** [review]
Possible to use layer/targets? Want to avoid becoming one of those projects that has like 15 Dockerfile files in root.

`docker/build-push-action@v4` supports `target`.

So the dockerfile could evolve into like:

 * Base
 * Beta
 * Prod (?)
 
So we only have 1.

**Comment by Fmstrat** [comment]
Yea, I actually started this using `INCLUDE+` but since only the absolute latest versions of Docker support it, I stopped that path.

After that I reorganized the Dockerfile but I now notice the install can always happen last, so targets should now work. I'll shift there.

**Comment by Fmstrat** [comment]
There we go, a single Dockerfile. Releases will be a bit slower because they'll build, but not really a big deal, and we retain the smaller image size. I can test this more fully once https://github.com/iBotPeaches/Apktool/issues/3362 is solved.

**Comment by iBotPeaches** [comment]
> Also, let me know if you'd prefer the beta workflow to be part of `build.yml` so that if a previous step fails they're connected.

There is a good deal of duplication, but since the entry point is different (published release vs merged pr) - I imagine that'll be difficult.

I'm guessing what might be easier is a composite workflow action we dump into `.github/actions/something` and that could do the publishing with inputs given from the respective workflows.

**Comment by Fmstrat** [comment]
Good point, that being said, it only triggers on a completed PR, so all the tests would have already run against the branch, so it probably doesn't actually matter.

**Comment by Fmstrat** [comment]
Updated to JDK/JRE 17 LTS. No longer blocked.

**Review by iBotPeaches — APPROVED** [review]

**Pull request merged**
