### PR TITLE
Comment out --forced-package-id, it might be not supported on windows

### PR DESCRIPTION
**Pull request by IlyaGazman**
- Added missing dependencies in gradle file for appache commons
 - Changed OS.exec(cmd.toArray(new String[0])); to OS.exec(cmd.toArray(new String[cmd.size()]));
 - Comment out --forced-package-id, it might be not supported on windows

### CODE REVIEW

**Comment by iBotPeaches** [comment]
So you updated the aapt binary for windows, but then disabled a feature that affects ALL platforms? Why did you add Apache Commons Lang?

You also have a few changes that are personalized in the `.local` file that shouldn't be in this PR.

Finally, where is this aapt from? Official? If so what version? Custom built? If so, source to repo.

**Comment by Ilya-Gazman** [comment]
First, tnx for replying me. I think you are doing a great job here!

I been trying to make this work, so I been playing with it mostly.

 - I took the AAPT from official build tools 23.03
 - I build my environment in Intellij and it missed the apache dependencies. Please tell me if there is a different way to add them.
 - About the local file, do you want to add this to .gitignore? Because it was Intellij who been playing with it.
 - I am not familiar with the " --forced-package-id" I wasn't been able to find docs about it. But once I comment it out, things start working again. Before that it been return exit code 2 from the command line task and that caused for the termination of the program. What code 2 stands for?

I will have more time to work on it, in Sunday. 
Please tell me what do you think.

**Comment by iBotPeaches** [comment]
Thanks for taking a stab and my initial response was probably too harsh. The `--forced-package-id` is a custom change we need to do special things. Due to other bugs, it seems this change wasn't propagated down to other binaries (it only works on linux/mac).

This mean for internal aapt binaries to work with apktool they need to work on all 3 platforms with that custom aapt patch (note to self - add windows testing). I think you were attempting to fix a bug that is only on windows, but the correct fix to is to re-implement the apktool patches to `frameworks/base` of the AOSP source and rebuild aapt.

I'll take a stab on it when I'm back in town. Still traveling so only available to respond to issues.

**Comment by technocode** [comment]
Still error... anyone want help me recompile this source?

Download link: https://www.dropbox.com/s/gtzpe3l1i500bws/WhatsApp.zip?dl=0

Thank you

**Comment by iBotPeaches** [comment]
I've updated the internal Windows aapt binary, so this shouldn't be a problem anymore.

**Pull request closed without merging**
