### PR TITLE
fix: decoding APK with many compact entries and unknown uses-sdk attrs

### PR DESCRIPTION
**Pull request by IgorEisberg**
This fixes 2 new issues with a stock APK sourced from an Android 15 ROM.

[https://drive.google.com/file/d/1x9udLN4W5I7chyGp1ZY8Cyfhu1vXezU9/view](https://drive.google.com/file/d/1x9udLN4W5I7chyGp1ZY8Cyfhu1vXezU9/view)
(classes files removed to reduce size, they are irrelevant)

1) mIn.readShort() for size in readEntryData is incorrect and the size < 0 check is not possible.
   Entry size is stored by AAPT2 as an unsigned short and thus will never be negative.
   Reading it as a signed short will cause negative entry sizes in compactly packed entries in
   very large string pools and will result in a lot of "APKTOOL_DUMMYVAL_" values.

2) sdkInfo isn't stored properly for APKs with unexpected properties in uses-sdk tag.
   As far as I can tell, these attributes serve no purpose and can be ignored.
   In the given APK, additional "android:versionCode" and "android:versionName" attributes appear
   in the uses-sdk tag, purpose unknown and they don't represent the actual version of the app.

```
   E: uses-sdk (line=26)
     A: http://schemas.android.com/apk/res/android:minSdkVersion(0x0101020c)=35
     A: http://schemas.android.com/apk/res/android:versionCode(0x0101021b)=31
     A: http://schemas.android.com/apk/res/android:versionName(0x0101021c)="3.1"
     A: http://schemas.android.com/apk/res/android:targetSdkVersion(0x01010270)=35
```

### CODE REVIEW

**Comment by iBotPeaches** [comment]
So we could build a sample of compactly packed resources that exceeds a signed short max (~32k) thus to trigger the flaw of reading a signed short vs unsigned

**Comment by IgorEisberg** [comment]
> So we could build a sample of compactly packed resources that exceeds a signed short max (~32k) thus to trigger the flaw of reading a signed short vs unsigned

Right, though the main reason we don't hit this issue often is because how many entries are required (+ them being compact) in order to hit the signed short max value of 32767, where the next size (= index) will become -32768.

**Comment by IgorEisberg** [comment]
Wrote the sample app. Could you write the test? Not really great at unit testing.
https://drive.google.com/file/d/1WF979N5qTWzGhQNtTMS8BET1dvPwecQ0/view

**Comment by iBotPeaches** [comment]
Easy source for sample? I like to keep sources for samples https://github.com/iBotPeaches/TestApks

**Comment by IgorEisberg** [comment]
> Easy source for sample? I like to keep sources for samples https://github.com/iBotPeaches/TestApks

Well... I didn't make a whole project just to compile a simple resources dir with the `--enable-compact-entries` flag passed to AAPT2. ^_^''

**Comment by iBotPeaches** [comment]
> Well... I didn't make a whole project just to compile a simple resources dir with the `--enable-compact-entries` flag passed to AAPT2. ^_^''

Fair, I always appreciate the reminder when it comes months later how I generated x. Sometimes I use a simple bash script to perform the actions if Gradle doesn't support it yet - https://github.com/iBotPeaches/TestApks/blob/master/ARSCTest/build.sh

**Review by iBotPeaches — APPROVED** [review]

**Pull request merged**
