### PR TITLE
fix: issue 1994

### PR DESCRIPTION
**Pull request by vbarthel-fr**
I have separated the changes into two commits:
- the first commit adds two tests that reproduce the bug. Those tests are failing:
- fixes: #1994 

```
brut.androlib.decode.DecodeArrayTest > decodeStringArray FAILED
    junit.framework.AssertionFailedError: Not a ResArrayValue. Found: class brut.androlib.res.data.value.ResStyleValue
        at junit.framework.Assert.fail(Assert.java:50)
        at junit.framework.Assert.assertTrue(Assert.java:20)
        at brut.androlib.decode.DecodeArrayTest.decodeStringArray(DecodeArrayTest.java:42)

brut.androlib.decode.DecodeArrayTest > decodeArray FAILED
    junit.framework.AssertionFailedError: Not a ResArrayValue. Found: class brut.androlib.res.data.value.ResStyleValue
        at junit.framework.Assert.fail(Assert.java:50)
        at junit.framework.Assert.assertTrue(Assert.java:20)
        at brut.androlib.decode.DecodeArrayTest.decodeArray(DecodeArrayTest.java:53)

141 tests completed, 2 failed
```

- the second commit adds the actual fix. The tests are now passing!

Note: for now I have kept the previous check on the id of the first item within the bag.
Note: I'm not 100% sure that the same technique could be applied to the `attr` resources. For now, only the `style`, `plurals`, and `array` have a new check on the res type spec name.

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Lucky #2000 :)

Everything looks good. If you wouldn't mind pushing the example app source code here - https://github.com/iBotPeaches/TestApks

Allows me to easily rebuild those applications if needed

**Comment by vbarthel-fr** [comment]
Sure! Here is the PR for the source code of the test apk: https://github.com/iBotPeaches/TestApks/pull/2

**Comment by iBotPeaches** [comment]
Thanks for the PR and very detailed commits. Makes it real easy for me!

**Comment by vbarthel-fr** [comment]
You're welcome :) Thanks a lot for all the work you have put into this project!

**Review by Doni108 — COMMENTED** [review]
Ok

**Pull request merged**
