### PR TITLE
Update dependencies & Add .editorconfig

### PR DESCRIPTION
**Pull request by Goooler**
- Update dependencies
- Add `.editorconfig` for format

### CODE REVIEW

**Review by iBotPeaches — COMMENTED** [review]
Going to dig into the editorconfig testing for a bit. Unsure since its `*` how that might affect all types of files that may/may-not like those configs.

**Comment by Goooler** [comment]
> testing

Don't worry, generally files need to be formatted are `*.java`.

**Comment by Goooler** [comment]
> Going to dig into the editorconfig testing for a bit. Unsure since its `*` how that might affect all types of files that may/may-not like those configs.

Don't worry, generally files need to be formatted are `*.java`.

**Review by iBotPeaches — APPROVED** [review]

**Comment by iBotPeaches** [comment]
thanks!

**Pull request merged**
